import { ReactNode } from "react";
import Head from "next/head";
import Header from "./header";

type MainLayoutProps = {
  children: ReactNode;
  title?: string;
};

const MainLayout = ({ children, title = "Default Title" }: MainLayoutProps) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>{children}</main>
      {/* <footer>
        <p>Footer content</p>
      </footer> */}
    </>
  );
};

export default MainLayout;
