import UserCard, { IUser } from "@/components/user-card";
import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";

export default function Home() {
  const [users, setUsers] = useState<IUser[] | []>([]);

  useEffect(() => {
    const fetchUsers = async () => {
      try {
        const res = await fetch("http://localhost:4000/api/users");
        const data = (await res.json()) as IUser[];
        setUsers(data);
      } catch (error) {
        console.log(error);
      }
    };

    // eslint-disable-next-line @typescript-eslint/no-floating-promises
    fetchUsers();
  }, []);
  return (
    <>
      <Head>
        <title>Stock Management</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <h1>Hello world!</h1>
        {users.map((user) => (
          <UserCard key={user.email} user={user} />
        ))}
      </main>
    </>
  );
}
